url: /
permalink: date
name: B&B Niemelän talo
menu:
    -
        text: Etusivu
        url: /
    -
        text: Majoitus
        url: /majoitus
        children:
            -
                text: Niemelän talo
                url: /majoitus/niemelän-talo.html
            -
                text: Rivitalo
                url: /majoitus/rivitalo.html
    -
        text: Tilaisuudet
        url: /tilaisuudet.html
    -
        text: Sauna
        url: /sauna.html
    -
        text: Hinnasto
        url: /hinnasto.html
    -
        text: Yhteystiedot
        url: /yhteystiedot.html
    -
        text: Ota yhteyttä
        url: /ota-yhteyttä.html
    -
        text: Linkit
        url: /linkit.html

exclude: [ 'sass', 'config.rb', 'Procfile', 'Thumbs.db' ]
relative_permalinks: false
markdown: kramdown
prose:
    rooturl: _posts
    metadata:
        _posts:
            - name: layout
              field:
                element: hidden
                value: default
            - name: permalink
              field:
                element: text
                label: URL
                value: 
            - name: lang
              field:
                element: select
                label: Kieli
                options:
                  - name: Suomi
                    value: fi
                  - name: Englanti
                    value: en
